FROM java:17

## jar 미생성 으로 주석
#ARG JAR_FILE=build/libs/example-api-0.0.1-SNAPSHOT.jar
#ADD ${JAR_FILE} sample.jar
#ENTRYPOINT ["java","-Xms1024m","-Xmx1024m","-jar","/sample.jar"]
# Spring Image End

